- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-python3-jobs
      - openstack-python3-next-jobs
    check:
      jobs:
        - barbican-tempest-plugin-simple-crypto-cursive
    gate:
      jobs:
        - barbican-tempest-plugin-simple-crypto-cursive
