---

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-python3-jobs
      - openstack-python3-next-jobs
    check:
      jobs:
        - barbican-tempest-plugin-simple-crypto-cursive:
            irrelevant-files: &irrelevant-files
              - ^\.coveragerc$
              - ^\.gitignore$
              - ^\.gitreview$
              - ^\.pre-commit-config\.yaml$
              - ^\.stestr\.conf$
              - ^.*\.rst$
              - ^doc/.*$
              - LICENSE
              - ^releasenotes/.*$
              - ^test-requirements\.txt$
              - ^tox\.ini$
              - ^cursive/tests/.*$
    gate:
      jobs:
        - barbican-tempest-plugin-simple-crypto-cursive:
            irrelevant-files: *irrelevant-files
